/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package integradorjava;

import BaseDatos.ConexionMySQL;
import java.awt.event.MouseAdapter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariel
 */
public class Devolucion extends javax.swing.JFrame {

    /**
     * Creates new form Devolucion
     */
    DefaultTableModel modelo;
    public Devolucion() {
        initComponents();
        CargarTablaPrestamo("","");
        tablaPrestamo.setEnabled(false);
        tablaPrestamo.addMouseListener(new MouseAdapter() {});//para q me tome el clic sobre una fila
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDev = new javax.swing.JButton();
        PnlSocioVista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamo = new javax.swing.JTable();
        txtBuscarsocio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarPrestamo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarIsbn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDev.setText("Devolucion");
        btnDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevActionPerformed(evt);
            }
        });

        PnlSocioVista.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda de Prestamo"));

        tablaPrestamo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPrestamo);

        txtBuscarsocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarsocioActionPerformed(evt);
            }
        });
        txtBuscarsocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarsocioKeyTyped(evt);
            }
        });

        jLabel4.setText("ingrese n°socio");

        btnBuscarPrestamo.setText("Buscar Prestamo");
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });

        jLabel5.setText("ingrese isbn");

        txtBuscarIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarIsbnActionPerformed(evt);
            }
        });
        txtBuscarIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarIsbnKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PnlSocioVistaLayout = new javax.swing.GroupLayout(PnlSocioVista);
        PnlSocioVista.setLayout(PnlSocioVistaLayout);
        PnlSocioVistaLayout.setHorizontalGroup(
            PnlSocioVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSocioVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlSocioVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlSocioVistaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarPrestamo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlSocioVistaLayout.setVerticalGroup(
            PnlSocioVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSocioVistaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PnlSocioVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarsocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscarPrestamo)
                    .addGroup(PnlSocioVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDev, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnlSocioVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(btnDev, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnlSocioVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtBuscarsocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarsocioKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') ) evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarsocioKeyTyped

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
      if((txtBuscarIsbn.getText().isEmpty() ||  txtBuscarsocio.getText().isEmpty())){
          JOptionPane.showMessageDialog(null, "debe rellenar ambos campos");
          CargarTablaPrestamo("","");
      }
      else{
        CargarTablaPrestamo(txtBuscarIsbn.getText(),txtBuscarsocio.getText());  
      }// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void btnDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevActionPerformed
//     ConexionMySQL mysql= new ConexionMySQL();
//        Connection cn= mysql.Conectar();
//        String sql= "";
//     sql="delete from prestamo where socio like '%"+txtBuscarsocio.getText()+"%' and isbn like '%"+txtBuscarIsbn.getText()+"%'";
//         try{    
//              PreparedStatement pst = cn.prepareStatement(sql);
     ActualizarEstadoLibro(txtBuscarIsbn.getText());
     ActualizarSocio(txtBuscarsocio.getText());
     ActualizarFdevolucion();
     CargarTablaPrestamo("","");
     
//       int n =pst.executeUpdate();
//            
//            if(n>0){
//            JOptionPane.showMessageDialog(null, "se ha devuelto de forma correcta");
//                 }
//     
//         }
//        catch (SQLException ex)
//        {
//           JOptionPane.showMessageDialog(null, ex);
//        }
    }//GEN-LAST:event_btnDevActionPerformed

    private void txtBuscarIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarIsbnKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') ) evt.consume();
    }//GEN-LAST:event_txtBuscarIsbnKeyTyped

    private void txtBuscarsocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarsocioActionPerformed
    txtBuscarsocio.transferFocus();        
    }//GEN-LAST:event_txtBuscarsocioActionPerformed

    private void txtBuscarIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarIsbnActionPerformed
     txtBuscarIsbn.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarIsbnActionPerformed

    private void tablaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrestamoMouseClicked
       int row = tablaPrestamo.rowAtPoint(tablaPrestamo.getMousePosition());

   /* row devolvera -1 si se ha clicado fuera de la fila pero dentro de la tabla, si no devolvera el indice de la fila en la que se ha clicado. */

   txtBuscarsocio.setText(tablaPrestamo.getValueAt(row, 4).toString());
   txtBuscarIsbn.setText(tablaPrestamo.getValueAt(row, 3).toString()); // TODO add your handling code here:
    }//GEN-LAST:event_tablaPrestamoMouseClicked
   public void ActualizarEstadoLibro(String isbn)   {
       ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        String sql= "";
        sql= "update libro set estado = ? where isbn = "+Integer.valueOf(isbn);
         try{
            PreparedStatement pst = cn.prepareStatement(sql);
            
            pst.setString(1, "libre");
             
                int n =pst.executeUpdate();
                if(n>0) 
                {//esto comprueba q se cargo todo
                     JOptionPane.showMessageDialog(null, "El libro pasara a estado libre");
                    CargarTablaPrestamo("","");
                    }
            }
        catch (SQLException ex)
        {
           JOptionPane.showMessageDialog(null, ex);
        }
   }
   String cantidad;
   public void ActualizarSocio(String socio){
       ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
       String sql="";
        Integer a=1;
        sql="select cantPrestamos from socio where socionum ="+Integer.valueOf(socio)+"";
       try{
           Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {  if (a==1){
                a=a+1;
                cantidad= rs.getString("cantPrestamos");
             } } 
            
        Integer cant= Integer.valueOf(cantidad);
        cant=cant-1;
       cambiaEstado(cant, socio);
       }
       catch(SQLException ex){
       JOptionPane.showMessageDialog(null, "llego hasta aca");}
   }
   public void cambiaEstado(Integer cant,String socio){
       ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
       String sql="";
        sql="update socio "
                + "set cantPrestamos = ?  "
                +"where socionum ="+Integer.valueOf(socio)+"";
        
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            String can =String.valueOf(cant);
            pst.setString(1, can);
             int n =pst.executeUpdate();
            
            if(n>0){
            JOptionPane.showMessageDialog(null, "se modifico el socio");
                 }        
                }
        catch (SQLException ex)
        {
           JOptionPane.showMessageDialog(null, ex);
        }}
   public void CargarTablaPrestamo(String isbn,String socio)    {
        String[] titulos = {"n°prestamo","fretiro","fdevolucion","isbn","socio"};
        String [] registro = new String[6];
        String sql= "";
        modelo= new DefaultTableModel(null,titulos);
        //para q me cintroduca datos al principio
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
        sql="select prestamo , fretiro , fdevolucion , isbn , socio  from prestamo "
                + "where socio like '%"+socio+"%' and isbn like '%"+isbn+"%' "
                + " and fdevolucion like 'nodevuelto'"; //para q me busque todos los tipos de coincidencia
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            //rs es una matriz q puedo recorrer
            while(rs.next())
            {
                registro[0]= rs.getString("prestamo");
                registro[1]= rs.getString("fretiro");
                registro[2]= rs.getString("fdevolucion");
                registro[3]= rs.getString("isbn");
                registro[4]= rs.getString("socio");
                
               
                modelo.addRow(registro);//agrego ese arreglo a la table para q se muestre
            }
            tablaPrestamo.setModel(modelo);
            
        } 
        catch (SQLException ex)
        {
           JOptionPane.showMessageDialog(null, ex);
        }
        
       
       
       
       
       
    }
   public void ActualizarFdevolucion(){
    ConexionMySQL mysql= new ConexionMySQL();
            Connection cn= mysql.Conectar();
            String sql="";
            sql="update prestamo "
                + "set fdevolucion = ?  "
                +"where socio like '%"+txtBuscarsocio.getText()+"%' and isbn like '%"+txtBuscarIsbn.getText()+"%'";
        
            try{
                    PreparedStatement pst = cn.prepareStatement(sql);
                    Date fecha=new Date(); 
                    SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                    String fechas=sdf.format(fecha);
                    pst.setString(1,fechas );
                int n =pst.executeUpdate();
      
                }
        catch (SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex);
                    }
        } 
   
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlSocioVista;
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnDev;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrestamo;
    private javax.swing.JTextField txtBuscarIsbn;
    private javax.swing.JTextField txtBuscarsocio;
    // End of variables declaration//GEN-END:variables
}
